#!/usr/bin/env python3
"""
prepare_assets.py — one-off generator for the 晨刊 MATINS brand assets.

Two kinds of output:

1. Computed geometry. The 破曉方塊 (Dawn Ramp) mark and the Bayer texture tile are
   *calculated*, not generated by an image model. The brand's geometry spec demands
   a mathematically regular ordered dither ("simulated or hand-scattered dots are
   off-brand"), and a Bayer matrix is cheaper to compute than to approximate.

2. Compressed artwork. The two approved dither paintings are cropped to their
   surface's aspect ratio, halved, and quantised. Measured autocorrelation on the
   source sky puts the dither cell at 5–6 px, so the paintings carry roughly a
   quarter of the information their pixel count implies: a NEAREST halving drops one
   whole cell-edge sample without touching the cell structure, and costs ~4x the file
   size. Lossy encoding is not an option here — an ordered dither is maximum-entropy
   to a DCT, so WebP q88 came out *larger* than lossless while smearing the grid that
   the brand calls its most protected asset.

   Quantisation runs with dither=NONE for the same reason: Pillow's default quantiser
   applies its *own* error-diffusion dither, which would scribble over the ordered
   Bayer grid. The sources carry 180k–460k colours only because of painterly
   blending; a median-cut to 16 is visually lossless on this material.

   Budget: every asset under 150 KB. Re-check after changing any knob below.

Re-run only when the source paintings or the mark geometry change.
"""

import subprocess
import sys
import urllib.parse
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "品牌視覺發想" / "確定視覺"
OUT = ROOT / "assets"

PAPER = "#FAF6ED"
INK = "#1A1612"
PAPER_DARK = "#14181E"
INK_DARK = "#EDE7DA"

# Ordered-dither threshold matrices. Values are compared against coverage * n**2.
BAYER4 = [
    [0, 8, 2, 10],
    [12, 4, 14, 6],
    [3, 11, 1, 9],
    [15, 7, 13, 5],
]
BAYER8 = [
    [0, 32, 8, 40, 2, 34, 10, 42],
    [48, 16, 56, 24, 50, 18, 58, 26],
    [12, 44, 4, 36, 14, 46, 6, 38],
    [60, 28, 52, 20, 62, 30, 54, 22],
    [3, 35, 11, 43, 1, 33, 9, 41],
    [51, 19, 59, 27, 49, 17, 57, 25],
    [15, 47, 7, 39, 13, 45, 5, 37],
    [63, 31, 55, 23, 61, 29, 53, 21],
]

# Coverage per band, bottom (index 0) to top, copied from the enumeration in
# brand-definition.md §"1 — The mark". Its geometry spec states the rule as
# (9 - n)/8, which would leave the top band at one eighth rather than the empty it
# also demands; the enumerated list is the one a human approved, so it wins. The
# uneven final step is deliberate — density falls off faster at the top, which is
# what makes the square read as first light rather than as a linear wedge.
BANDS = [8 / 8, 7 / 8, 6 / 8, 5 / 8, 4 / 8, 3 / 8, 1 / 8, 0.0]


# --------------------------------------------------------------------------- marks


def ramp_runs() -> list[tuple[int, int, int]]:
    """The Dawn Ramp as (x, y, width) runs on a 32x32 grid, y=0 at the top.

    Every cell in the square is thresholded against one shared Bayer lattice indexed
    by absolute position, so the columns line up from the bottom band to the top —
    that alignment is what separates a dither ramp from eight rows of scattered dots.
    """
    size = 32
    runs = []
    for y in range(size):
        coverage = BANDS[len(BANDS) - 1 - (y // 4)]
        threshold = coverage * 16
        x = 0
        while x < size:
            if BAYER4[y % 4][x % 4] < threshold:
                start = x
                while x < size and BAYER4[y % 4][x % 4] < threshold:
                    x += 1
                runs.append((start, y, x - start))
            else:
                x += 1
    return runs


def ramp_path() -> str:
    """The ramp as one path. ~470 runs as <rect> elements cost 10 KB; as subpaths of
    a single `d` they cost under 3 KB, which matters because the mask copy of this
    lands inline in a stylesheet that is duplicated into every archived page."""
    return "".join(f"M{x} {y}h{w}v1h-{w}z" for x, y, w in ramp_runs())


def write_favicon() -> Path:
    """Two-colour, edge to edge, theme-aware. No margin: it has to survive 16px."""
    svg = (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" '
        'role="img" aria-label="晨刊 MATINS">'
        "<style>"
        f".bg{{fill:{PAPER}}}.ink{{fill:{INK}}}"
        "@media (prefers-color-scheme:dark){"
        f".bg{{fill:{PAPER_DARK}}}.ink{{fill:{INK_DARK}}}}}"
        "</style>"
        '<rect class="bg" width="32" height="32"/>'
        f'<path class="ink" shape-rendering="crispEdges" d="{ramp_path()}"/>'
        "</svg>"
    )
    path = ROOT / "favicon.svg"
    path.write_text(svg, encoding="utf-8")
    return path


def mark_data_uri() -> str:
    """The mark as a CSS mask source — colour comes from the page, not the file.

    Used as a mask rather than an <img> so the empty state and the end mark inherit
    currentColor and stay correct in both themes without shipping two files.
    """
    svg = (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">'
        f'<path d="{ramp_path()}"/>'
        "</svg>"
    )
    return "data:image/svg+xml," + urllib.parse.quote(svg, safe="")


def texture_data_uri() -> str:
    """Bayer 8x8 at 50% coverage — the paper the brand is printed on."""
    d = []
    for y in range(8):
        x = 0
        while x < 8:
            if BAYER8[y][x] < 32:
                start = x
                while x < 8 and BAYER8[y][x] < 32:
                    x += 1
                d.append(f"M{start} {y}h{x - start}v1h-{x - start}z")
            else:
                x += 1
    svg = (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 8 8" width="8" height="8">'
        f'<path d="{"".join(d)}"/>'
        "</svg>"
    )
    return "data:image/svg+xml," + urllib.parse.quote(svg, safe="")


# ------------------------------------------------------------------------- artwork


def crop_band(im: Image.Image, ratio: float, focus: float) -> Image.Image:
    """Crop to `ratio` (w/h), keeping `focus` (0..1) as the vertical centre of interest."""
    w, h = im.size
    target_h = round(w / ratio)
    if target_h <= h:
        top = round(focus * h - target_h / 2)
        top = max(0, min(h - target_h, top))
        return im.crop((0, top, w, top + target_h))
    target_w = round(h * ratio)
    left = max(0, min(w - target_w, (w - target_w) // 2))
    return im.crop((left, 0, left + target_w, h))


def encode(im: Image.Image, stem: str, colors: int) -> Path:
    """Quantise, then keep whichever of PNG-8 / lossless WebP comes out smaller."""
    quant = im.convert("RGB").quantize(
        colors=colors, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE
    )

    png = OUT / f"{stem}.png"
    quant.save(png, format="PNG", optimize=True)

    webp = OUT / f"{stem}.webp"
    try:
        subprocess.run(
            ["cwebp", "-quiet", "-lossless", "-z", "9", str(png), "-o", str(webp)],
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return png

    # Drop the loser so a flip between runs cannot leave a stale twin behind.
    if webp.stat().st_size < png.stat().st_size:
        png.unlink()
        return webp
    webp.unlink()
    return png


def kb(path: Path) -> str:
    return f"{path.stat().st_size / 1024:.0f} KB"


def main() -> int:
    OUT.mkdir(exist_ok=True)

    fav = write_favicon()
    print(f"  favicon.svg                 {kb(fav)}")

    WATERFALL = "ChatGPT Image Aug 8 2026 from Image Generation Request (5).png"
    jobs = [
        # (source, stem, aspect ratio, vertical focus, NEAREST divisor, palette)
        ("demo.png", "masthead-engraving", 4.0, 0.42, 1, 12),
        ("demo.png", "og", 1200 / 628, 0.46, 2, 16),
        (WATERFALL, "notfound", None, None, 2, 16),
    ]

    # The nameplate is exempt: it is the hero of all 115 pages and is served at
    # full resolution so a 1180px broadsheet downscales it rather than blowing up
    # its dither grid. Everything else stays lean.
    budget_kb = {"masthead-engraving": 200}
    over = []
    for name, stem, ratio, focus, div, colors in jobs:
        src = SRC / name
        if not src.exists():
            print(f"!! missing source: {name}")
            return 1
        im = Image.open(src).convert("RGB")
        if ratio:
            im = crop_band(im, ratio, focus)
        # NEAREST only: any interpolating filter averages neighbouring dither cells
        # into new intermediate colours, which both blurs the grid and defeats the
        # palette reduction below.
        im = im.resize((im.width // div, im.height // div), Image.NEAREST)
        out = encode(im, stem, colors)
        print(f"  {out.name:27s} {kb(out):>7s}  {im.size[0]}x{im.size[1]}")
        if out.stat().st_size > budget_kb.get(stem, 150) * 1024:
            over.append(out.name)

    if over:
        print(f"\n!! over budget: {', '.join(over)}")
        return 1

    # Emitted as a module rather than pasted, so the favicon on disk and the mask
    # inside the stylesheet can never drift out of geometry with each other.
    module = ROOT / "dither_assets.py"
    module.write_text(
        '"""Generated by tools/prepare_assets.py — do not edit by hand.\n\n'
        "Ordered-dither geometry shared by the stylesheet: the 破曉方塊 mark as a CSS\n"
        "mask source, and the Bayer 8x8 paper texture tile.\n"
        '"""\n\n'
        f'MARK_URI = "{mark_data_uri()}"\n\n'
        f'TEXTURE_URI = "{texture_data_uri()}"\n',
        encoding="utf-8",
    )
    print(f"  dither_assets.py            {kb(module)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
